/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { customFetch } from './fetch-instance';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

/**
 * Represents a tag/label for categorizing entries
 */
export type TagDto = {
  /** Unique identifier of the tag */
  id?: number;
  /**
   * Name/title of the tag
   * @maxLength 100
   */
  title: string;
  /**
   * Detailed description of the tag
   * @maxLength 500
   */
  description?: string;
  /**
   * Icon associated with the tag (emoji or code)
   * @maxLength 50
   */
  icon?: string;
  /**
   * Sort order for display
   * @minimum 0
   */
  sortingOrder: number;
  /**
   * ISO 4217 currency code (3 letters)
   * @minLength 3
   * @maxLength 3
   */
  currencyCode?: string;
  /** Whether the tag represents cumulative values */
  isCumulative?: boolean;
  /** Whether the tag is hidden from display */
  hidden?: boolean;
};

/**
 * Recurrence frequency
 */
export type RecurrenceDtoFrequency = typeof RecurrenceDtoFrequency[keyof typeof RecurrenceDtoFrequency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurrenceDtoFrequency = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  YEARLY: 'YEARLY',
  NONE: 'NONE',
} as const;

/**
 * Represents a recurring financial transaction
 */
export type RecurrenceDto = {
  /** Unique identifier of the recurrence */
  id?: number;
  /** Last modification date (managed automatically) */
  readonly modificationDate?: string;
  /**
   * Title or label of the recurrence
   * @maxLength 255
   */
  title: string;
  /**
   * Detailed description of the recurrence
   * @maxLength 1000
   */
  description?: string;
  /** Transaction amount (positive for credit, negative for debit) */
  amount: number;
  /**
   * ISO 4217 currency code (3 letters)
   * @minLength 3
   * @maxLength 3
   */
  currencyCode: string;
  /** Start date of the recurrence */
  startDate: string;
  /** Recurrence frequency */
  frequency: RecurrenceDtoFrequency;
  /** List of tags associated with this recurrence */
  tags?: TagDto[];
};

/**
 * Represents an exchange rate between two currencies
 */
export type RateDto = {
  /** Unique identifier of the exchange rate */
  readonly id?: number;
  /**
   * ISO 4217 code of the source currency
   * @minLength 3
   * @maxLength 3
   */
  sourceCurrencyCode: string;
  /**
   * ISO 4217 code of the target currency (reference currency)
   * @minLength 3
   * @maxLength 3
   */
  targetCurrencyCode: string;
  /** Validity date of the exchange rate */
  valueDate: string;
  /** Exchange rate value (1 unit of source = rate units of target) */
  rate: number;
};

/**
 * Represents a defined time period
 */
export type PeriodDto = {
  /** Unique identifier of the period */
  readonly id?: number;
  /**
   * Title or name of the period
   * @maxLength 255
   */
  title: string;
  /** Start date and time of the period */
  startDate: string;
  /** End date and time of the period */
  endDate: string;
  /**
   * ISO 4217 currency code (3 letters)
   * @minLength 3
   * @maxLength 3
   * @nullable
   */
  currencyCode?: string | null;
  /** Whether the period is hidden from display */
  hidden?: boolean;
};

/**
 * Represents a financial entry (transaction)
 */
export type EntryDto = {
  /** Unique identifier of the entry */
  id?: number;
  /** Accounting date of the transaction */
  accountingDate: string;
  /** Last modification date (managed automatically) */
  readonly modificationDate?: string;
  /**
   * Title or label of the entry
   * @maxLength 255
   */
  title: string;
  /**
   * Detailed description of the transaction
   * @maxLength 1000
   */
  description?: string;
  /** Transaction amount (positive for credit, negative for debit) */
  amount: number;
  /**
   * ISO 4217 currency code (3 letters)
   * @minLength 3
   * @maxLength 3
   */
  currencyCode: string;
  /** List of tags/labels associated with this entry */
  tags?: TagDto[];
};

/**
 * Represents a monetary currency
 */
export type CurrencyDto = {
  /**
   * ISO 4217 currency code (3 uppercase letters)
   * @minLength 3
   * @maxLength 3
   */
  code: string;
  /** Whether this currency is the reference currency */
  reference?: boolean;
};

/**
 * Request for aggregated amount calculation over a period
 */
export type ComputationRequestDto = {
  /** Start date of the calculation period */
  startDate: string;
  /** End date of the calculation period */
  endDate: string;
  /** List of tags to filter entries in the calculation */
  tags?: TagDto[];
  /** Search text */
  searchText?: string;
  /**
   * ISO 4217 code of the target currency for conversion (reference currency or tag currency)
   * @minLength 3
   * @maxLength 3
   */
  targetCurrencyCode: string;
};

/**
 * Breakdown of aggregated calculation for a specific currency
 */
export type ComputationCurrencyAmountDto = {
  /** ISO 4217 currency code */
  currencyCode?: string;
  /** Number of entries in this currency */
  numberOfEntries?: number;
  /** Total amount in this currency (before conversion) */
  totalAmount?: number;
};

/**
 * Breakdown of calculations by source currency (key = currency code, value = calculation details)
 */
export type ComputationResponseDtoComputationByCurrency = {[key: string]: ComputationCurrencyAmountDto};

/**
 * Result of aggregated amount calculation
 */
export type ComputationResponseDto = {
  /** Start date of the calculated period */
  startDate?: string;
  /** End date of the calculated period */
  endDate?: string;
  /** Total amount converted to the target currency */
  totalAmount?: number;
  /** ISO 4217 code of the target currency used for conversion */
  targetCurrencyCode?: string;
  /** Total number of entries included in the calculation */
  numberOfEntries?: number;
  /** Breakdown of calculations by source currency (key = currency code, value = calculation details) */
  computationByCurrency?: ComputationResponseDtoComputationByCurrency;
};

export type PageImplTagDto = {
  content?: TagDto[];
  pageable?: PageableObject;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
  numberOfElements?: number;
  size?: number;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
};

export type PageableObject = {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
  offset?: number;
  sort?: SortObject;
};

export type SortObject = {
  sorted?: boolean;
  unsorted?: boolean;
  empty?: boolean;
};

/**
 * Represents a group of tags frequently used together
 */
export type TagGroupDto = {
  /** Unique identifier of the tag group */
  id?: number;
  /** Number of times this tag group has been used */
  usageCount?: number;
  /** Date and time this tag group was last used */
  lastUsed?: string;
  /** Tags belonging to this group */
  tags?: TagDto[];
};

/**
 * Represents a suggested title for a tag group
 */
export type TagGroupTitleSuggestionDto = {
  /** Unique identifier of the suggestion */
  id?: number;
  /** Identifier of the associated tag group */
  tagGroupId: number;
  /**
   * Suggested title
   * @maxLength 255
   */
  title: string;
  /** Number of times this suggestion has been used */
  usageCount?: number;
  /** Date and time this suggestion was last used */
  lastUsed?: string;
};

export type PageImplRecurrenceDto = {
  content?: RecurrenceDto[];
  pageable?: PageableObject;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
  numberOfElements?: number;
  size?: number;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
};

export type PageImplRateDto = {
  content?: RateDto[];
  pageable?: PageableObject;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
  numberOfElements?: number;
  size?: number;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
};

export type PageImplPeriodDto = {
  content?: PeriodDto[];
  pageable?: PageableObject;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
  numberOfElements?: number;
  size?: number;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
};

export type PageImplEntryDto = {
  content?: EntryDto[];
  pageable?: PageableObject;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
  numberOfElements?: number;
  size?: number;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
};

export type PageImplCurrencyDto = {
  content?: CurrencyDto[];
  pageable?: PageableObject;
  totalElements?: number;
  totalPages?: number;
  last?: boolean;
  first?: boolean;
  numberOfElements?: number;
  size?: number;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
};

export type GetTagsParams = {
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

export type UploadIconBody = {
  file: Blob;
};

export type GetRecurrencesParams = {
/**
 * Start date filter (inclusive)
 */
startDate?: string;
/**
 * End date filter (inclusive)
 */
endDate?: string;
/**
 * List of tag IDs to filter recurrences
 */
tagIds?: number[];
/**
 * Frequencies to filter recurrences
 */
frequencies?: GetRecurrencesFrequenciesItem[];
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

/**
 * Frequencies to filter recurrences
 */
export type GetRecurrencesFrequenciesItem = typeof GetRecurrencesFrequenciesItem[keyof typeof GetRecurrencesFrequenciesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRecurrencesFrequenciesItem = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  YEARLY: 'YEARLY',
  NONE: 'NONE',
} as const;

export type GetRatesParams = {
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

export type GetPeriodsParams = {
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

export type GetEntriesParams = {
/**
 * Start date of the search period (inclusive)
 */
startDate?: string;
/**
 * End date of the search period (inclusive)
 */
endDate?: string;
/**
 * List of tag IDs to filter entries
 */
tagIds?: number[];
/**
 * Minimum transaction amount
 */
startAmount?: number;
/**
 * Maximum transaction amount
 */
endAmount?: number;
/**
 * Currency codes to filter entries (ISO 4217 codes)
 */
currencyCodes?: string[];
/**
 * Text search on title and description (case-insensitive, partial match)
 */
searchText?: string;
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

export type GetCurrenciesParams = {
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

export type GetTagGroupsParams = {
/**
 * List of tag IDs to filter tag groups
 */
tagIds?: number[];
};

export type SimulateEntriesParams = {
/**
 * Date de début de la période (inclusive)
 */
fromDate: string;
/**
 * Date de fin de la période (inclusive)
 */
toDate: string;
};

export type GetRatesByCurrencyParams = {
/**
 * Page number (starts at 0)
 * @minimum 0
 * @maximum 2147483647
 */
page?: number;
/**
 * Number of elements per page
 * @minimum 1
 * @maximum 1000
 */
size?: number;
/**
 * Sort criteria (format: 'property:direction' where direction = asc|desc)
 */
sort?: string[];
};

export type GetPeriodByDateParams = {
/**
 * Date à rechercher
 */
date: string;
};

/**
 * Retourne un tag spécifique
 * @summary Récupérer un tag par son ID
 */
export type getTagByIdResponse200 = {
  data: TagDto
  status: 200
}

export type getTagByIdResponse404 = {
  data: void
  status: 404
}
    
export type getTagByIdResponseSuccess = (getTagByIdResponse200) & {
  headers: Headers;
};
export type getTagByIdResponseError = (getTagByIdResponse404) & {
  headers: Headers;
};

export type getTagByIdResponse = (getTagByIdResponseSuccess | getTagByIdResponseError)

export const getGetTagByIdUrl = (id: number,) => {


  

  return `/tags/${id}`
}

export const getTagById = async (id: number, options?: RequestInit): Promise<getTagByIdResponse> => {
  
  return customFetch<getTagByIdResponse>(getGetTagByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Met à jour un tag existant
 * @summary Mettre à jour un tag
 */
export type updateTagResponse200 = {
  data: TagDto
  status: 200
}

export type updateTagResponse400 = {
  data: void
  status: 400
}

export type updateTagResponse404 = {
  data: void
  status: 404
}
    
export type updateTagResponseSuccess = (updateTagResponse200) & {
  headers: Headers;
};
export type updateTagResponseError = (updateTagResponse400 | updateTagResponse404) & {
  headers: Headers;
};

export type updateTagResponse = (updateTagResponseSuccess | updateTagResponseError)

export const getUpdateTagUrl = (id: number,) => {


  

  return `/tags/${id}`
}

export const updateTag = async (id: number,
    tagDto: TagDto, options?: RequestInit): Promise<updateTagResponse> => {
  
  return customFetch<updateTagResponse>(getUpdateTagUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tagDto,)
  }
);}



/**
 * Supprime un tag définitivement
 * @summary Supprimer un tag
 */
export type deleteTagResponse204 = {
  data: void
  status: 204
}

export type deleteTagResponse404 = {
  data: void
  status: 404
}
    
export type deleteTagResponseSuccess = (deleteTagResponse204) & {
  headers: Headers;
};
export type deleteTagResponseError = (deleteTagResponse404) & {
  headers: Headers;
};

export type deleteTagResponse = (deleteTagResponseSuccess | deleteTagResponseError)

export const getDeleteTagUrl = (id: number,) => {


  

  return `/tags/${id}`
}

export const deleteTag = async (id: number, options?: RequestInit): Promise<deleteTagResponse> => {
  
  return customFetch<deleteTagResponse>(getDeleteTagUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Retourne une récurrence spécifique identifiée par son ID
 * @summary Récupérer une récurrence par son ID
 */
export type getRecurrenceByIdResponse200 = {
  data: RecurrenceDto
  status: 200
}

export type getRecurrenceByIdResponse404 = {
  data: void
  status: 404
}
    
export type getRecurrenceByIdResponseSuccess = (getRecurrenceByIdResponse200) & {
  headers: Headers;
};
export type getRecurrenceByIdResponseError = (getRecurrenceByIdResponse404) & {
  headers: Headers;
};

export type getRecurrenceByIdResponse = (getRecurrenceByIdResponseSuccess | getRecurrenceByIdResponseError)

export const getGetRecurrenceByIdUrl = (id: number,) => {


  

  return `/recurrences/${id}`
}

export const getRecurrenceById = async (id: number, options?: RequestInit): Promise<getRecurrenceByIdResponse> => {
  
  return customFetch<getRecurrenceByIdResponse>(getGetRecurrenceByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Met à jour une récurrence existante avec les nouvelles informations fournies
 * @summary Mettre à jour une récurrence
 */
export type updateRecurrenceResponse200 = {
  data: RecurrenceDto
  status: 200
}

export type updateRecurrenceResponse400 = {
  data: void
  status: 400
}

export type updateRecurrenceResponse404 = {
  data: void
  status: 404
}
    
export type updateRecurrenceResponseSuccess = (updateRecurrenceResponse200) & {
  headers: Headers;
};
export type updateRecurrenceResponseError = (updateRecurrenceResponse400 | updateRecurrenceResponse404) & {
  headers: Headers;
};

export type updateRecurrenceResponse = (updateRecurrenceResponseSuccess | updateRecurrenceResponseError)

export const getUpdateRecurrenceUrl = (id: number,) => {


  

  return `/recurrences/${id}`
}

export const updateRecurrence = async (id: number,
    recurrenceDto: NonReadonly<RecurrenceDto>, options?: RequestInit): Promise<updateRecurrenceResponse> => {
  
  return customFetch<updateRecurrenceResponse>(getUpdateRecurrenceUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recurrenceDto,)
  }
);}



/**
 * Supprime définitivement une récurrence existante
 * @summary Supprimer une récurrence
 */
export type deleteRecurrenceResponse204 = {
  data: void
  status: 204
}

export type deleteRecurrenceResponse404 = {
  data: void
  status: 404
}
    
export type deleteRecurrenceResponseSuccess = (deleteRecurrenceResponse204) & {
  headers: Headers;
};
export type deleteRecurrenceResponseError = (deleteRecurrenceResponse404) & {
  headers: Headers;
};

export type deleteRecurrenceResponse = (deleteRecurrenceResponseSuccess | deleteRecurrenceResponseError)

export const getDeleteRecurrenceUrl = (id: number,) => {


  

  return `/recurrences/${id}`
}

export const deleteRecurrence = async (id: number, options?: RequestInit): Promise<deleteRecurrenceResponse> => {
  
  return customFetch<deleteRecurrenceResponse>(getDeleteRecurrenceUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Retourne un taux de change spécifique
 * @summary Récupérer un taux par son ID
 */
export type getRateByIdResponse200 = {
  data: RateDto
  status: 200
}

export type getRateByIdResponse404 = {
  data: void
  status: 404
}
    
export type getRateByIdResponseSuccess = (getRateByIdResponse200) & {
  headers: Headers;
};
export type getRateByIdResponseError = (getRateByIdResponse404) & {
  headers: Headers;
};

export type getRateByIdResponse = (getRateByIdResponseSuccess | getRateByIdResponseError)

export const getGetRateByIdUrl = (id: number,) => {


  

  return `/rates/${id}`
}

export const getRateById = async (id: number, options?: RequestInit): Promise<getRateByIdResponse> => {
  
  return customFetch<getRateByIdResponse>(getGetRateByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Met à jour un taux de change existant
 * @summary Mettre à jour un taux
 */
export type updateRateResponse200 = {
  data: RateDto
  status: 200
}

export type updateRateResponse400 = {
  data: void
  status: 400
}

export type updateRateResponse404 = {
  data: void
  status: 404
}
    
export type updateRateResponseSuccess = (updateRateResponse200) & {
  headers: Headers;
};
export type updateRateResponseError = (updateRateResponse400 | updateRateResponse404) & {
  headers: Headers;
};

export type updateRateResponse = (updateRateResponseSuccess | updateRateResponseError)

export const getUpdateRateUrl = (id: number,) => {


  

  return `/rates/${id}`
}

export const updateRate = async (id: number,
    rateDto: NonReadonly<RateDto>, options?: RequestInit): Promise<updateRateResponse> => {
  
  return customFetch<updateRateResponse>(getUpdateRateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rateDto,)
  }
);}



/**
 * Supprime un taux de change
 * @summary Supprimer un taux
 */
export type deleteRateResponse204 = {
  data: void
  status: 204
}

export type deleteRateResponse404 = {
  data: void
  status: 404
}
    
export type deleteRateResponseSuccess = (deleteRateResponse204) & {
  headers: Headers;
};
export type deleteRateResponseError = (deleteRateResponse404) & {
  headers: Headers;
};

export type deleteRateResponse = (deleteRateResponseSuccess | deleteRateResponseError)

export const getDeleteRateUrl = (id: number,) => {


  

  return `/rates/${id}`
}

export const deleteRate = async (id: number, options?: RequestInit): Promise<deleteRateResponse> => {
  
  return customFetch<deleteRateResponse>(getDeleteRateUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Retourne une période spécifique
 * @summary Récupérer une période par son ID
 */
export type getPeriodByIdResponse200 = {
  data: PeriodDto
  status: 200
}

export type getPeriodByIdResponse404 = {
  data: void
  status: 404
}
    
export type getPeriodByIdResponseSuccess = (getPeriodByIdResponse200) & {
  headers: Headers;
};
export type getPeriodByIdResponseError = (getPeriodByIdResponse404) & {
  headers: Headers;
};

export type getPeriodByIdResponse = (getPeriodByIdResponseSuccess | getPeriodByIdResponseError)

export const getGetPeriodByIdUrl = (id: number,) => {


  

  return `/periods/${id}`
}

export const getPeriodById = async (id: number, options?: RequestInit): Promise<getPeriodByIdResponse> => {
  
  return customFetch<getPeriodByIdResponse>(getGetPeriodByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Met à jour une période comptable existante
 * @summary Mettre à jour une période
 */
export type updatePeriodResponse200 = {
  data: PeriodDto
  status: 200
}

export type updatePeriodResponse400 = {
  data: void
  status: 400
}

export type updatePeriodResponse404 = {
  data: void
  status: 404
}
    
export type updatePeriodResponseSuccess = (updatePeriodResponse200) & {
  headers: Headers;
};
export type updatePeriodResponseError = (updatePeriodResponse400 | updatePeriodResponse404) & {
  headers: Headers;
};

export type updatePeriodResponse = (updatePeriodResponseSuccess | updatePeriodResponseError)

export const getUpdatePeriodUrl = (id: number,) => {


  

  return `/periods/${id}`
}

export const updatePeriod = async (id: number,
    periodDto: NonReadonly<PeriodDto>, options?: RequestInit): Promise<updatePeriodResponse> => {
  
  return customFetch<updatePeriodResponse>(getUpdatePeriodUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      periodDto,)
  }
);}



/**
 * Supprime une période comptable
 * @summary Supprimer une période
 */
export type deletePeriodResponse204 = {
  data: void
  status: 204
}

export type deletePeriodResponse404 = {
  data: void
  status: 404
}
    
export type deletePeriodResponseSuccess = (deletePeriodResponse204) & {
  headers: Headers;
};
export type deletePeriodResponseError = (deletePeriodResponse404) & {
  headers: Headers;
};

export type deletePeriodResponse = (deletePeriodResponseSuccess | deletePeriodResponseError)

export const getDeletePeriodUrl = (id: number,) => {


  

  return `/periods/${id}`
}

export const deletePeriod = async (id: number, options?: RequestInit): Promise<deletePeriodResponse> => {
  
  return customFetch<deletePeriodResponse>(getDeletePeriodUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Retourne une entrée spécifique identifiée par son ID
 * @summary Récupérer une entrée par son ID
 */
export type getEntryByIdResponse200 = {
  data: EntryDto
  status: 200
}

export type getEntryByIdResponse404 = {
  data: void
  status: 404
}
    
export type getEntryByIdResponseSuccess = (getEntryByIdResponse200) & {
  headers: Headers;
};
export type getEntryByIdResponseError = (getEntryByIdResponse404) & {
  headers: Headers;
};

export type getEntryByIdResponse = (getEntryByIdResponseSuccess | getEntryByIdResponseError)

export const getGetEntryByIdUrl = (id: number,) => {


  

  return `/entries/${id}`
}

export const getEntryById = async (id: number, options?: RequestInit): Promise<getEntryByIdResponse> => {
  
  return customFetch<getEntryByIdResponse>(getGetEntryByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Met à jour une entrée existante avec les nouvelles informations fournies
 * @summary Mettre à jour une entrée
 */
export type updateEntryResponse200 = {
  data: EntryDto
  status: 200
}

export type updateEntryResponse400 = {
  data: void
  status: 400
}

export type updateEntryResponse404 = {
  data: void
  status: 404
}
    
export type updateEntryResponseSuccess = (updateEntryResponse200) & {
  headers: Headers;
};
export type updateEntryResponseError = (updateEntryResponse400 | updateEntryResponse404) & {
  headers: Headers;
};

export type updateEntryResponse = (updateEntryResponseSuccess | updateEntryResponseError)

export const getUpdateEntryUrl = (id: number,) => {


  

  return `/entries/${id}`
}

export const updateEntry = async (id: number,
    entryDto: NonReadonly<EntryDto>, options?: RequestInit): Promise<updateEntryResponse> => {
  
  return customFetch<updateEntryResponse>(getUpdateEntryUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      entryDto,)
  }
);}



/**
 * Supprime définitivement une entrée existante
 * @summary Supprimer une entrée
 */
export type deleteEntryResponse204 = {
  data: void
  status: 204
}

export type deleteEntryResponse404 = {
  data: void
  status: 404
}
    
export type deleteEntryResponseSuccess = (deleteEntryResponse204) & {
  headers: Headers;
};
export type deleteEntryResponseError = (deleteEntryResponse404) & {
  headers: Headers;
};

export type deleteEntryResponse = (deleteEntryResponseSuccess | deleteEntryResponseError)

export const getDeleteEntryUrl = (id: number,) => {


  

  return `/entries/${id}`
}

export const deleteEntry = async (id: number, options?: RequestInit): Promise<deleteEntryResponse> => {
  
  return customFetch<deleteEntryResponse>(getDeleteEntryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Retourne une liste paginée de tous les tags
 * @summary Récupérer tous les tags
 */
export type getTagsResponse200 = {
  data: PageImplTagDto
  status: 200
}
    
export type getTagsResponseSuccess = (getTagsResponse200) & {
  headers: Headers;
};
;

export type getTagsResponse = (getTagsResponseSuccess)

export const getGetTagsUrl = (params?: GetTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tags?${stringifiedParams}` : `/tags`
}

export const getTags = async (params?: GetTagsParams, options?: RequestInit): Promise<getTagsResponse> => {
  
  return customFetch<getTagsResponse>(getGetTagsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Crée un nouveau tag/étiquette
 * @summary Créer un nouveau tag
 */
export type createTagResponse201 = {
  data: TagDto
  status: 201
}

export type createTagResponse400 = {
  data: void
  status: 400
}
    
export type createTagResponseSuccess = (createTagResponse201) & {
  headers: Headers;
};
export type createTagResponseError = (createTagResponse400) & {
  headers: Headers;
};

export type createTagResponse = (createTagResponseSuccess | createTagResponseError)

export const getCreateTagUrl = () => {


  

  return `/tags`
}

export const createTag = async (tagDto: TagDto, options?: RequestInit): Promise<createTagResponse> => {
  
  return customFetch<createTagResponse>(getCreateTagUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tagDto,)
  }
);}



/**
 * @summary Uploader une icône pour un tag
 */
export type uploadIconResponse200 = {
  data: TagDto
  status: 200
}

export type uploadIconResponse400 = {
  data: TagDto
  status: 400
}

export type uploadIconResponse404 = {
  data: TagDto
  status: 404
}
    
export type uploadIconResponseSuccess = (uploadIconResponse200) & {
  headers: Headers;
};
export type uploadIconResponseError = (uploadIconResponse400 | uploadIconResponse404) & {
  headers: Headers;
};

export type uploadIconResponse = (uploadIconResponseSuccess | uploadIconResponseError)

export const getUploadIconUrl = (id: number,) => {


  

  return `/tags/${id}/icon`
}

export const uploadIcon = async (id: number,
    uploadIconBody: UploadIconBody, options?: RequestInit): Promise<uploadIconResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadIconBody.file)

  return customFetch<uploadIconResponse>(getUploadIconUrl(id),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}



/**
 * Retourne une liste paginée de récurrences filtrées selon les critères fournis
 * @summary Récupérer toutes les récurrences
 */
export type getRecurrencesResponse200 = {
  data: PageImplRecurrenceDto
  status: 200
}
    
export type getRecurrencesResponseSuccess = (getRecurrencesResponse200) & {
  headers: Headers;
};
;

export type getRecurrencesResponse = (getRecurrencesResponseSuccess)

export const getGetRecurrencesUrl = (params?: GetRecurrencesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tagIds","frequencies","sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/recurrences?${stringifiedParams}` : `/recurrences`
}

export const getRecurrences = async (params?: GetRecurrencesParams, options?: RequestInit): Promise<getRecurrencesResponse> => {
  
  return customFetch<getRecurrencesResponse>(getGetRecurrencesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Crée une nouvelle transaction récurrente avec les informations fournies
 * @summary Créer une nouvelle récurrence
 */
export type createRecurrenceResponse201 = {
  data: RecurrenceDto
  status: 201
}

export type createRecurrenceResponse400 = {
  data: void
  status: 400
}
    
export type createRecurrenceResponseSuccess = (createRecurrenceResponse201) & {
  headers: Headers;
};
export type createRecurrenceResponseError = (createRecurrenceResponse400) & {
  headers: Headers;
};

export type createRecurrenceResponse = (createRecurrenceResponseSuccess | createRecurrenceResponseError)

export const getCreateRecurrenceUrl = () => {


  

  return `/recurrences`
}

export const createRecurrence = async (recurrenceDto: NonReadonly<RecurrenceDto>, options?: RequestInit): Promise<createRecurrenceResponse> => {
  
  return customFetch<createRecurrenceResponse>(getCreateRecurrenceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recurrenceDto,)
  }
);}



/**
 * Retourne une liste paginée de tous les taux de change
 * @summary Récupérer tous les taux de change
 */
export type getRatesResponse200 = {
  data: PageImplRateDto
  status: 200
}
    
export type getRatesResponseSuccess = (getRatesResponse200) & {
  headers: Headers;
};
;

export type getRatesResponse = (getRatesResponseSuccess)

export const getGetRatesUrl = (params?: GetRatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/rates?${stringifiedParams}` : `/rates`
}

export const getRates = async (params?: GetRatesParams, options?: RequestInit): Promise<getRatesResponse> => {
  
  return customFetch<getRatesResponse>(getGetRatesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Crée un nouveau taux de change
 * @summary Créer un nouveau taux
 */
export type createRateResponse201 = {
  data: RateDto
  status: 201
}

export type createRateResponse400 = {
  data: void
  status: 400
}
    
export type createRateResponseSuccess = (createRateResponse201) & {
  headers: Headers;
};
export type createRateResponseError = (createRateResponse400) & {
  headers: Headers;
};

export type createRateResponse = (createRateResponseSuccess | createRateResponseError)

export const getCreateRateUrl = () => {


  

  return `/rates`
}

export const createRate = async (rateDto: NonReadonly<RateDto>, options?: RequestInit): Promise<createRateResponse> => {
  
  return customFetch<createRateResponse>(getCreateRateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rateDto,)
  }
);}



/**
 * Retourne une liste paginée de toutes les périodes comptables
 * @summary Récupérer toutes les périodes
 */
export type getPeriodsResponse200 = {
  data: PageImplPeriodDto
  status: 200
}
    
export type getPeriodsResponseSuccess = (getPeriodsResponse200) & {
  headers: Headers;
};
;

export type getPeriodsResponse = (getPeriodsResponseSuccess)

export const getGetPeriodsUrl = (params?: GetPeriodsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/periods?${stringifiedParams}` : `/periods`
}

export const getPeriods = async (params?: GetPeriodsParams, options?: RequestInit): Promise<getPeriodsResponse> => {
  
  return customFetch<getPeriodsResponse>(getGetPeriodsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Crée une nouvelle période comptable
 * @summary Créer une nouvelle période
 */
export type createPeriodResponse201 = {
  data: PeriodDto
  status: 201
}

export type createPeriodResponse400 = {
  data: void
  status: 400
}
    
export type createPeriodResponseSuccess = (createPeriodResponse201) & {
  headers: Headers;
};
export type createPeriodResponseError = (createPeriodResponse400) & {
  headers: Headers;
};

export type createPeriodResponse = (createPeriodResponseSuccess | createPeriodResponseError)

export const getCreatePeriodUrl = () => {


  

  return `/periods`
}

export const createPeriod = async (periodDto: NonReadonly<PeriodDto>, options?: RequestInit): Promise<createPeriodResponse> => {
  
  return customFetch<createPeriodResponse>(getCreatePeriodUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      periodDto,)
  }
);}



/**
 * Retourne une liste paginée d'entrées filtrées selon les critères de recherche fournis
 * @summary Récupérer toutes les entrées
 */
export type getEntriesResponse200 = {
  data: PageImplEntryDto
  status: 200
}
    
export type getEntriesResponseSuccess = (getEntriesResponse200) & {
  headers: Headers;
};
;

export type getEntriesResponse = (getEntriesResponseSuccess)

export const getGetEntriesUrl = (params?: GetEntriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tagIds","currencyCodes","sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/entries?${stringifiedParams}` : `/entries`
}

export const getEntries = async (params?: GetEntriesParams, options?: RequestInit): Promise<getEntriesResponse> => {
  
  return customFetch<getEntriesResponse>(getGetEntriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Crée une nouvelle entrée financière avec les informations fournies
 * @summary Créer une nouvelle entrée
 */
export type createEntryResponse201 = {
  data: EntryDto
  status: 201
}

export type createEntryResponse400 = {
  data: void
  status: 400
}
    
export type createEntryResponseSuccess = (createEntryResponse201) & {
  headers: Headers;
};
export type createEntryResponseError = (createEntryResponse400) & {
  headers: Headers;
};

export type createEntryResponse = (createEntryResponseSuccess | createEntryResponseError)

export const getCreateEntryUrl = () => {


  

  return `/entries`
}

export const createEntry = async (entryDto: NonReadonly<EntryDto>, options?: RequestInit): Promise<createEntryResponse> => {
  
  return customFetch<createEntryResponse>(getCreateEntryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      entryDto,)
  }
);}



/**
 * Crée plusieurs entrées financières en une seule transaction
 * @summary Créer plusieurs entrées en lot
 */
export type createBatchResponse201 = {
  data: EntryDto
  status: 201
}

export type createBatchResponse400 = {
  data: void
  status: 400
}
    
export type createBatchResponseSuccess = (createBatchResponse201) & {
  headers: Headers;
};
export type createBatchResponseError = (createBatchResponse400) & {
  headers: Headers;
};

export type createBatchResponse = (createBatchResponseSuccess | createBatchResponseError)

export const getCreateBatchUrl = () => {


  

  return `/entries/batch`
}

export const createBatch = async (entryDto: NonReadonly<EntryDto[]>, options?: RequestInit): Promise<createBatchResponse> => {
  
  return customFetch<createBatchResponse>(getCreateBatchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      entryDto,)
  }
);}



/**
 * Retourne une liste paginée de toutes les devises
 * @summary Récupérer toutes les devises
 */
export type getCurrenciesResponse200 = {
  data: PageImplCurrencyDto
  status: 200
}
    
export type getCurrenciesResponseSuccess = (getCurrenciesResponse200) & {
  headers: Headers;
};
;

export type getCurrenciesResponse = (getCurrenciesResponseSuccess)

export const getGetCurrenciesUrl = (params?: GetCurrenciesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/currencies?${stringifiedParams}` : `/currencies`
}

export const getCurrencies = async (params?: GetCurrenciesParams, options?: RequestInit): Promise<getCurrenciesResponse> => {
  
  return customFetch<getCurrenciesResponse>(getGetCurrenciesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Crée une nouvelle devise
 * @summary Créer une nouvelle devise
 */
export type createCurrencyResponse201 = {
  data: CurrencyDto
  status: 201
}

export type createCurrencyResponse400 = {
  data: void
  status: 400
}
    
export type createCurrencyResponseSuccess = (createCurrencyResponse201) & {
  headers: Headers;
};
export type createCurrencyResponseError = (createCurrencyResponse400) & {
  headers: Headers;
};

export type createCurrencyResponse = (createCurrencyResponseSuccess | createCurrencyResponseError)

export const getCreateCurrencyUrl = () => {


  

  return `/currencies`
}

export const createCurrency = async (currencyDto: CurrencyDto, options?: RequestInit): Promise<createCurrencyResponse> => {
  
  return customFetch<createCurrencyResponse>(getCreateCurrencyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      currencyDto,)
  }
);}



/**
 * Calcule la somme des montants fournis en appliquant les taux de change appropriés pour convertir dans la devise cible
 * @summary Calculer la somme avec conversion de devises
 */
export type computeResponse200 = {
  data: ComputationResponseDto
  status: 200
}

export type computeResponse400 = {
  data: void
  status: 400
}
    
export type computeResponseSuccess = (computeResponse200) & {
  headers: Headers;
};
export type computeResponseError = (computeResponse400) & {
  headers: Headers;
};

export type computeResponse = (computeResponseSuccess | computeResponseError)

export const getComputeUrl = () => {


  

  return `/computation`
}

export const compute = async (computationRequestDto: ComputationRequestDto, options?: RequestInit): Promise<computeResponse> => {
  
  return customFetch<computeResponse>(getComputeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      computationRequestDto,)
  }
);}



/**
 * @summary Récupérer les groupes de tags contenant au moins un des tags donnés
 */
export type getTagGroupsResponse200 = {
  data: TagGroupDto[]
  status: 200
}
    
export type getTagGroupsResponseSuccess = (getTagGroupsResponse200) & {
  headers: Headers;
};
;

export type getTagGroupsResponse = (getTagGroupsResponseSuccess)

export const getGetTagGroupsUrl = (params?: GetTagGroupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tagIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tag-groups?${stringifiedParams}` : `/tag-groups`
}

export const getTagGroups = async (params?: GetTagGroupsParams, options?: RequestInit): Promise<getTagGroupsResponse> => {
  
  return customFetch<getTagGroupsResponse>(getGetTagGroupsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Récupérer les suggestions de titres pour un groupe de tags, triées par popularité
 */
export type getTitleSuggestionsResponse200 = {
  data: TagGroupTitleSuggestionDto[]
  status: 200
}
    
export type getTitleSuggestionsResponseSuccess = (getTitleSuggestionsResponse200) & {
  headers: Headers;
};
;

export type getTitleSuggestionsResponse = (getTitleSuggestionsResponseSuccess)

export const getGetTitleSuggestionsUrl = (id: number,) => {


  

  return `/tag-groups/${id}/title-suggestions`
}

export const getTitleSuggestions = async (id: number, options?: RequestInit): Promise<getTitleSuggestionsResponse> => {
  
  return customFetch<getTitleSuggestionsResponse>(getGetTitleSuggestionsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Retourne les entrées qui seraient générées par les récurrences actives entre fromDate et toDate
 * @summary Simuler les entrées récurrentes sur une période
 */
export type simulateEntriesResponse200 = {
  data: EntryDto[]
  status: 200
}
    
export type simulateEntriesResponseSuccess = (simulateEntriesResponse200) & {
  headers: Headers;
};
;

export type simulateEntriesResponse = (simulateEntriesResponseSuccess)

export const getSimulateEntriesUrl = (params: SimulateEntriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/recurrences/simulate?${stringifiedParams}` : `/recurrences/simulate`
}

export const simulateEntries = async (params: SimulateEntriesParams, options?: RequestInit): Promise<simulateEntriesResponse> => {
  
  return customFetch<simulateEntriesResponse>(getSimulateEntriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Retourne les taux de change pour une devise spécifique
 * @summary Récupérer les taux par devise
 */
export type getRatesByCurrencyResponse200 = {
  data: RateDto[]
  status: 200
}
    
export type getRatesByCurrencyResponseSuccess = (getRatesByCurrencyResponse200) & {
  headers: Headers;
};
;

export type getRatesByCurrencyResponse = (getRatesByCurrencyResponseSuccess)

export const getGetRatesByCurrencyUrl = (currencyCode: string,
    params?: GetRatesByCurrencyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/rates/currency/${currencyCode}?${stringifiedParams}` : `/rates/currency/${currencyCode}`
}

export const getRatesByCurrency = async (currencyCode: string,
    params?: GetRatesByCurrencyParams, options?: RequestInit): Promise<getRatesByCurrencyResponse> => {
  
  return customFetch<getRatesByCurrencyResponse>(getGetRatesByCurrencyUrl(currencyCode,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Retourne la période comptable contenant une date spécifique
 * @summary Récupérer une période par date
 */
export type getPeriodByDateResponse200 = {
  data: PeriodDto
  status: 200
}

export type getPeriodByDateResponse404 = {
  data: void
  status: 404
}
    
export type getPeriodByDateResponseSuccess = (getPeriodByDateResponse200) & {
  headers: Headers;
};
export type getPeriodByDateResponseError = (getPeriodByDateResponse404) & {
  headers: Headers;
};

export type getPeriodByDateResponse = (getPeriodByDateResponseSuccess | getPeriodByDateResponseError)

export const getGetPeriodByDateUrl = (params: GetPeriodByDateParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/periods/by-date?${stringifiedParams}` : `/periods/by-date`
}

export const getPeriodByDate = async (params: GetPeriodByDateParams, options?: RequestInit): Promise<getPeriodByDateResponse> => {
  
  return customFetch<getPeriodByDateResponse>(getGetPeriodByDateUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Retourne une devise spécifique identifiée par son code ISO
 * @summary Récupérer une devise par son code
 */
export type getCurrencyByCodeResponse200 = {
  data: CurrencyDto
  status: 200
}

export type getCurrencyByCodeResponse404 = {
  data: void
  status: 404
}
    
export type getCurrencyByCodeResponseSuccess = (getCurrencyByCodeResponse200) & {
  headers: Headers;
};
export type getCurrencyByCodeResponseError = (getCurrencyByCodeResponse404) & {
  headers: Headers;
};

export type getCurrencyByCodeResponse = (getCurrencyByCodeResponseSuccess | getCurrencyByCodeResponseError)

export const getGetCurrencyByCodeUrl = (code: string,) => {


  

  return `/currencies/${code}`
}

export const getCurrencyByCode = async (code: string, options?: RequestInit): Promise<getCurrencyByCodeResponse> => {
  
  return customFetch<getCurrencyByCodeResponse>(getGetCurrencyByCodeUrl(code),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Supprime une devise
 * @summary Supprimer une devise
 */
export type deleteCurrencyResponse204 = {
  data: void
  status: 204
}

export type deleteCurrencyResponse404 = {
  data: void
  status: 404
}
    
export type deleteCurrencyResponseSuccess = (deleteCurrencyResponse204) & {
  headers: Headers;
};
export type deleteCurrencyResponseError = (deleteCurrencyResponse404) & {
  headers: Headers;
};

export type deleteCurrencyResponse = (deleteCurrencyResponseSuccess | deleteCurrencyResponseError)

export const getDeleteCurrencyUrl = (code: string,) => {


  

  return `/currencies/${code}`
}

export const deleteCurrency = async (code: string, options?: RequestInit): Promise<deleteCurrencyResponse> => {
  
  return customFetch<deleteCurrencyResponse>(getDeleteCurrencyUrl(code),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
